builders:
  info:
    import: "package:gitsumu/gitsumu.dart"
    builder_factories: [ "infoBuilder" ]
    build_extensions: { ".dart": [ ".git.dart" ] }
    auto_apply: dependents
    build_to: source
