name: gitsumu
description: Dart package generates git info.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  collection: ^1.18.0
  source_gen: ^1.4.0
  path: ^1.8.0
  args: ^2.4.2
  build_config: ^1.1.1
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0




